tubes1/app2/urls.py
from django.urls import path

from . import views

app_name = 'app2'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tubes1/crudex/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('del/<slug:del_product>', views.delete),
    path('update/<slug:update_product>', views.update),
]

tubes1/tubes1/urls.py
from django.contrib import admin
from django.urls import include,path
from crudex import views
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app2/', include('app2.urls')),
    path('crudex/', include('crudex.urls')),
    path('',views.homepage, name='homepage'),
]

tubes1/app2/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField (default=0)
    def __str__(self):
        return self.choice_text

tubes1/crudex/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    product_value=models.CharField(max_length=100)
    def __str__(self):
        return self.product_value

tubes1/home/models.py
from django.db import models

# Create your models here.

tubes1/crudex/forms.py
from django import forms
from crudex.models import Product

class ProductForm(forms.ModelForm):
    product_value =  forms.CharField(max_length=100, help_text = "Enter Name Product")

    class Meta:
        model = Product
        fields = ('product_value',)

tubes1/app2/views.py
#from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Question
from django.http import Http404
 


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('app2/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'app2/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

tubes1/crudex/views.py
from django.shortcuts import render, redirect
from crudex.models import Product
from crudex.forms import ProductForm

# Create your views here.
def index(request):
    products_from_db = Product.objects.all()
    form = ProductForm()
    context_dict={'products_from_context': products_from_db, 'form':form}
    if request.method == 'POST':
            form = ProductForm(request.POST)
            if form.is_valid():
                form.save(commit=True)
                return render(request, 'crudex/index.html', context_dict)
            else:
                print(form.errors)
        
    return render (request, 'crudex/index.html', context_dict)

def delete(request,del_product):
    products_from_db = Product.objects.all()
    form = ProductForm()
    context_dict={'products_from_context': products_from_db, 'form':form}
    if request.method == 'POST':
        del_product= Product.objects.get(product_value= del_product)
        del_product.delete()
    return render(request, 'crudex/index.html', context_dict)

def update(request,update_product):
    products_from_db = Product.objects.all()
    form = ProductForm()
    context_dict={'products_from_context': products_from_db, 'form':form}
    if request.method == 'POST':
        update_product= Product.objects.get(product_value= update_product)
        update_product.update()
    return render(request, 'crudex/index.html', context_dict)

tubes1/home/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')

tubes1/app2/templates/app2/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

<h3>Terimakasih</h3>
<button type="button" onclick="history.back()">Back</button>

tubes1/app2/templates/app2/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'app2:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

tubes1/crudex/templates/crudex/index.html
<!DOCTYPE html>
<html>
<head>
    <title>crudex</title>
</head>
<body>
    <h2>Selamat Datang di 7Digital Website</h2>
    <p>Tempat Create, Update, dan Delete data Produk Kamera</p>
    {% if products_from_context %}
            <ul>
                {% for product in products_from_context %}
                    <li>{{ product.product_value }} 
                        <form id = "product_form" method="post" action="/crudex/del/{{ product.product_value }}">
                            {% csrf_token %} <input type="submit" product="submit" value="Delete">
                        </form>
                        <form id ="product_form" method="POST" action="/">
                            {% csrf_token %}
                            {% for field in form.visible_fields %}
                                {{ field.errors }}
                                {{ field.help_text}}
                                {{ field }}
                            {% endfor %}
                            <input type="submit" product="submit" value="Update">
                        </form>
                    </li>
                {% endfor %}
            </ul>
    {% else %}
        <h3>Please Go to Admin and add a New Product under 'CRUDEX'</h3>
    {% endif %}

    <h3>add a Product</h3>
    <form id ="product_form" method="POST" action="/">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text}}
            {{ field }}
        {% endfor %}
        <input type="submit" product="submit" value="Create">
    </form>
    
</body>
</html>

tubes1/home/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <style>
        body {
          padding-top: 5px;
          padding-bottom: 5px;
          }
        .navbar {
          margin-bottom: 5px;
          }
      </style>
    </head>
</head>
<body>
    <header>
        <h1>Selamat Datang Di 7Digital Website</h1>
        <h2>Ini adalah Website untuk memenuhi nilai UTS Mata kuliah Python</h2>
        
        <div>
         <ul>
            <li><a href="/crudex/">List Product</a></li>
            <li><a href="/app2/">Kelompok 7</a></li>
        </ul> 
        </div>
        
    </header>
</body>
    
</html>